# Generated by Django 3.1.7 on 2021-04-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalendarzapp', '0004_auto_20210415_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, null=True)),
                ('history', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
