# Generated by Django 3.1.7 on 2021-04-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalendarzapp', '0005_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='Historia',
        ),
        migrations.RenameModel(
            old_name='Meeting',
            new_name='Spotkania',
        ),
    ]
