# Generated by Django 3.1.7 on 2021-04-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalendarzapp', '0006_auto_20210415_1715'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Historia',
            new_name='Historie',
        ),
        migrations.RenameModel(
            old_name='Spotkania',
            new_name='Meeting',
        ),
    ]
