# Generated by Django 3.1.7 on 2021-05-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalendarzapp', '0008_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='historie',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
